question_data = [
    {"category": "General Knowledge",
     "type": "multiple",
     "difficulty": "easy",
     "question": "What is the largest organ of the human body?",
     "correct_answer": "Skin",
     "incorrect_answers": ["Heart", "large Intestine", "Liver"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which of the following languages is used as a scripting language in the Unity 3D game engine?",
     "correct_answer": "C#", "incorrect_answers": ["Java", "C++", "Objective-C"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
     "question": "How many planets make up our Solar System?", "correct_answer": "8",
     "incorrect_answers": ["7", "9", "6"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
     "question": "The colour of the pills in the Matrix were Blue and Yellow.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "easy",
     "question": "How many times do you fight Gilgamesh in &quot;Final Fantasy 5&quot;?",
     "correct_answer": "6", "incorrect_answers": ["4", "5", "3"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "medium",
     "question": "In &quot;Team Fortress 2&quot;, the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "multiple", "difficulty": "easy",
     "question": "When did the Battle of the Somme begin?",
     "correct_answer": "July 1st, 1916",
     "incorrect_answers": ["August 1st, 1916", "July 2nd, 1916", "June 30th, 1916"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "easy",
     "question": "Who is the leader of Team Instinct in Pok&eacute;mon Go?",
     "correct_answer": "Spark", "incorrect_answers": ["Candela", "Blanche", "Willow"]},
    {"category": "Entertainment: Television", "type": "multiple",
     "difficulty": "medium",
     "question": "In &quot;The Big Bang Theory&quot;, what is Howard Wolowitz&#039;s nickname in World of Warcraft?",
     "correct_answer": "Wolowizard",
     "incorrect_answers": ["Sheldor", "Rajesh", "Priya"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "What is the name of New Zealand&#039;s indigenous people?",
     "correct_answer": "Maori",
     "incorrect_answers": ["Vikings", "Polynesians", "Samoans"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "medium",
     "question": "When was the video game &quot;P.A.M.E.L.A.&quot; released on Steam?",
     "correct_answer": "March 9, 2017",
     "incorrect_answers": ["January 7, 2007", "October 23, 1997",
                           "February 16, 2015"]},
    {"category": "Politics", "type": "multiple", "difficulty": "medium",
     "question": "Before 2016, in which other year did Donald Trump run for President?",
     "correct_answer": "2000", "incorrect_answers": ["2012", "1988", "2008"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Books", "type": "multiple", "difficulty": "medium",
     "question": "What is the name of Eragon&#039;s dragon in &quot;Eragon&quot;?",
     "correct_answer": "Saphira", "incorrect_answers": ["Glaedr", "Thorn", "Arya"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "easy",
     "question": "Which Pok&eacute;mon can learn the move &quot;Secret Power&quot; by leveling up?",
     "correct_answer": "Audino",
     "incorrect_answers": ["Type:Null", "Arceus", "Silvally"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
     "question": "What Nickelodeon game show featured a house on the set that the contestants would ransack to find hidden objects?",
     "correct_answer": "Finders Keepers",
     "incorrect_answers": ["Double Dare", "Nickelodeon Guts", "Nick Arcade"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
     "question": "What TV show is about a grandfather dragging his grandson around on adventures?",
     "correct_answer": "Rick &amp; Morty",
     "incorrect_answers": ["Family Guy", "South Park", "American Dad"]},
    {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
     "question": "The Harry Potter series of books, combined, are over 1,000,000 words in length.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "medium",
     "question": "In the co-op shooter Payday 2, which contact helps you break out Hoxton?",
     "correct_answer": "The Dentist",
     "incorrect_answers": ["Vlad", "The Elephant", "The Butcher"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "hard",
     "question": "Who is a minor god that is protector and creator of various arts, such as cheese making and bee keeping.",
     "correct_answer": "Aristaeus",
     "incorrect_answers": ["Autonoe", "Carme", "Cephisso"]}
]
